server {
    listen 8080;
    server_name _;
    server_tokens off;

    root /usr/share/nginx/html;
    index index.html;

    include /etc/nginx/security-headers.conf;

    location = /config.js {
        include /etc/nginx/security-headers.conf;
        add_header Cache-Control "no-store";
        try_files $uri =404;
        limit_except GET { deny all; }
    }

    location / {
        try_files $uri $uri/ /index.html;
        limit_except GET { deny all; }
    }
}
