#!/usr/bin/env sh
set -eu

/bin/cat > .env.ci << 'EOF'
COMPOSE_PROJECT_NAME=docpilot_ci
JWT_SECRET_KEY=ci-test-secret-not-for-production
OPENAI_API_KEY=ci-fake-openai-key
POSTGRES_DB=docpilot_ci
POSTGRES_USER=docpilot_ci
POSTGRES_PASSWORD=docpilot_ci_password
BACKEND_PORT=8000
FRONTEND_PORT=5500
DOCPILOT_AI_MODEL=gpt-4o-mini
DOCPILOT_EMBEDDING_MODEL=text-embedding-3-small
DOCPILOT_EMBEDDING_BATCH_SIZE=100
DOCPILOT_RETRIEVAL_TOP_K=5
DOCPILOT_RETRIEVAL_MIN_SCORE=0.0
DOCPILOT_EVAL_MAX_LATENCY_MS=5000.0
DOCPILOT_EVAL_MIN_CONTEXT_REDUCTION=50.0
DOCPILOT_EVAL_MIN_CITATION_PRESERVATION=0.8
DOCPILOT_EVAL_PERSIST_RESULTS=true
DOCPILOT_CONVERSATION_MAX_MESSAGES=10
DOCPILOT_TRUSTED_HOSTS=localhost,127.0.0.1,testserver
EOF

/bin/echo "Generated .env.ci with non-sensitive CI defaults."
